feat:dag from cluster-trace-v2018
340Lab/serverless_sim pull request #87
Opened 2024-12-01 12:29 UTC by oreki-white

2024-12-29 06:57 UTC, ActivePeter requested changes

2024-12-29 06:57 UTC, ActivePeter commented on serverless_sim/src/request.rs
> +    // fn print_dag_dependencies(dag: &FnDAG) {
remove

2024-12-29 06:57 UTC, ActivePeter commented on serverless_sim/src/request.rs
>      fn init_metrics(&mut self, env: &SimEnv) {
给这个函数加一个测试，保证可靠性

2024-12-30 07:34 UTC, oreki-white commented on serverless_sim/src/request.rs
> +    // fn print_dag_dependencies(dag: &FnDAG) {
already remove

2024-12-30 07:34 UTC, oreki-white commented on serverless_sim/src/request.rs
>      fn init_metrics(&mut self, env: &SimEnv) {
已经加了

2025-01-02 06:29 UTC, merged